--
-- PostgreSQL database dump
--

\restrict TYyDwbouFhGmbIwUnRb4etM6IiYWgNocppu7STdcaOAB9nk8QUfxvWIvD3hjlC4

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-06 02:08:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16517)
-- Name: ActivityLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ActivityLogs" (
    "Id" integer NOT NULL,
    "Action" text NOT NULL,
    "Description" text NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL
);


ALTER TABLE public."ActivityLogs" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16516)
-- Name: ActivityLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ActivityLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ActivityLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16543)
-- Name: Assets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Assets" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "serialNumber" text NOT NULL,
    "Category" text NOT NULL,
    "Status" text NOT NULL,
    "UserId" integer
);


ALTER TABLE public."Assets" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16542)
-- Name: Assets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Assets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Assets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16561)
-- Name: Tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tickets" (
    "Id" integer NOT NULL,
    "Subject" text NOT NULL,
    "Description" text NOT NULL,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AssetId" integer,
    "UserId" integer,
    "CreatedById" integer,
    "Resolution" text
);


ALTER TABLE public."Tickets" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16560)
-- Name: Tickets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tickets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tickets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16529)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    role text NOT NULL,
    status text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16528)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16509)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5042 (class 0 OID 16517)
-- Dependencies: 221
-- Data for Name: ActivityLogs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ActivityLogs" ("Id", "Action", "Description", "Timestamp") FROM stdin;
1	USER_REGISTER	New user registered: anisazrina99@gmail.com	2026-09-05 04:29:02.442403+08
2	USER_REGISTER	New user registered: sarahanim@test.com	2026-09-05 04:31:01.508332+08
3	USER_REGISTER	New user registered: samdol@test.com	2026-09-05 04:31:24.274088+08
4	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 04:31:35.822866+08
5	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 04:33:05.625079+08
6	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 04:33:20.87573+08
7	CREATE_TICKET	Ticket ID 1 (Maintenance Request: Macbook Pro M1 (SN-4836)) created for User ID 2.	2026-09-05 04:33:47.475838+08
8	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 04:33:57.360338+08
9	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 04:38:25.144454+08
10	USER_LOGIN	User logged in: samdol@test.com	2026-09-05 04:38:45.362084+08
11	CREATE_TICKET	Ticket ID 2 (Maintenance Request: Asus Tuf (SN-8465)) created for User ID 3.	2026-09-05 04:38:56.034899+08
12	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 04:39:00.257691+08
13	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 05:03:20.932126+08
14	USER_LOGIN	User logged in: samdol@test.com	2026-09-05 05:04:00.997711+08
15	CREATE_TICKET	Ticket ID 3 (Maintenance Request: Dell (SN-4765)) created for User ID 3.	2026-09-05 05:04:10.526603+08
16	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 05:04:26.9212+08
17	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 05:04:33.894315+08
18	USER_LOGIN	User logged in: samdol@test.com	2026-09-05 05:41:57.22272+08
19	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 05:42:13.714141+08
20	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 05:42:22.76998+08
21	CREATE_TICKET	Ticket ID 4 (Maintenance Request: Dell (SN-4765)) created for User ID 3.	2026-09-05 05:55:37.41219+08
22	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 16:32:48.04555+08
23	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 16:39:29.971362+08
24	USER_REGISTER	New user registered: sarahanim@test.com	2026-09-05 20:51:16.147635+08
25	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 20:51:24.63228+08
26	USER_REGISTER	New user registered: akmalhakim@test.com	2026-09-05 20:52:07.826211+08
27	USER_REGISTER	New user registered: wanshamil@test.com	2026-09-05 20:53:11.706192+08
28	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 20:53:21.839491+08
29	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 21:14:31.865092+08
30	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 21:14:32.898485+08
31	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:14:46.195929+08
32	USER_LOGIN	User logged in: sarahanim@test.com	2026-09-05 21:14:55.308105+08
33	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:14:59.613675+08
34	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 21:19:50.648947+08
35	CREATE_TICKET	Ticket ID 5 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) created for User ID 5.	2026-09-05 21:25:07.710075+08
36	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:31:18.488999+08
37	UPDATE_TICKET	Ticket ID 5 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 21:35:38.967253+08
38	DELETE_TICKET	Tiket ID 5 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) has been deleted.	2026-09-05 21:35:53.334474+08
39	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 21:36:24.383555+08
40	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:36:46.02016+08
41	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 21:37:13.766951+08
42	CREATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) created for User ID 5.	2026-09-05 21:40:33.249443+08
43	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:40:50.128271+08
44	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 21:47:20.049537+08
45	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 21:52:45.489103+08
46	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 21:53:11.071282+08
47	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 21:53:15.429672+08
48	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 21:58:09.935639+08
49	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Open.	2026-09-05 21:59:17.612117+08
50	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 21:59:20.602792+08
51	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 21:59:26.351866+08
52	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 22:01:12.58424+08
53	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 22:02:51.838147+08
54	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:05:07.869562+08
55	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:05:19.582823+08
56	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:05:52.062727+08
57	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 22:06:06.907643+08
58	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:06:34.222907+08
59	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 22:10:16.156248+08
60	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 22:10:19.465175+08
61	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 22:10:23.180173+08
63	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 22:15:10.180412+08
64	UPDATE_TICKET	Ticket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 22:15:14.541258+08
65	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:15:20.362897+08
66	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 22:15:30.323752+08
67	DELETE_TICKET	Tiket ID 6 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) has been deleted.	2026-09-05 22:19:49.832376+08
68	CREATE_TICKET	Ticket ID 7 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) created for User ID 5.	2026-09-05 22:20:15.099325+08
69	DELETE_TICKET	Tiket ID 7 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) has been deleted.	2026-09-05 22:20:26.155736+08
70	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 22:20:29.36991+08
71	CREATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) created for User ID 5.	2026-09-05 22:20:49.004542+08
72	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 22:22:32.512974+08
73	UPDATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 22:41:11.07128+08
74	UPDATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 23:11:16.155224+08
75	UPDATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Open.	2026-09-05 23:19:55.443143+08
76	UPDATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 23:19:58.722282+08
77	UPDATE_TICKET	Ticket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 23:20:03.21644+08
78	DELETE_TICKET	Tiket ID 8 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) has been deleted.	2026-09-05 23:29:24.038503+08
79	USER_LOGIN	User logged in: akmalhakim@test.com	2026-09-05 23:29:30.234478+08
80	CREATE_TICKET	Ticket ID 9 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) created for User ID 5.	2026-09-05 23:29:43.989283+08
81	USER_LOGIN	User logged in: anisazrina99@gmail.com	2026-09-05 23:30:11.548427+08
82	UPDATE_TICKET	Ticket ID 9 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to In Progress.	2026-09-05 23:32:34.646389+08
83	UPDATE_TICKET	Ticket ID 9 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 23:34:30.486429+08
84	UPDATE_TICKET	Ticket ID 9 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Open.	2026-09-05 23:35:34.948256+08
85	UPDATE_TICKET	Ticket ID 9 (Maintenance Request: HP EliteDisplay E223 (SN-9362)) status updated to Resolved.	2026-09-05 23:35:46.327063+08
\.


--
-- TOC entry 5046 (class 0 OID 16543)
-- Dependencies: 225
-- Data for Name: Assets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Assets" ("Id", "Name", "serialNumber", "Category", "Status", "UserId") FROM stdin;
5	Macbook Pro M1 	SN-3254	Laptop	In Use	4
6	Macbook Pro M2 	SN-8463	Laptop	In Use	5
7	Asus Vivobook	SN-9164	Laptop	In Use	6
8	HP EliteDisplay E223	SN-9362	Monitor	Maintenance	5
\.


--
-- TOC entry 5048 (class 0 OID 16561)
-- Dependencies: 227
-- Data for Name: Tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tickets" ("Id", "Subject", "Description", "Status", "Priority", "CreatedAt", "AssetId", "UserId", "CreatedById", "Resolution") FROM stdin;
9	Maintenance Request: HP EliteDisplay E223 (SN-9362)	The laptop screen flickers intermittently.	Resolved	Medium	2026-09-05 23:35:34.947936+08	8	5	\N	test 2
\.


--
-- TOC entry 5044 (class 0 OID 16529)
-- Dependencies: 223
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", username, email, password, role, status) FROM stdin;
1	Anis Azrina	anisazrina99@gmail.com	12345678	Admin	Active
4	Sarah Hanim	sarahanim@test.com	12345678	Staff	Active
5	Akmal Hakim	akmalhakim@test.com	12345678	Staff	Active
6	Wan Shamil	wanshamil@test.com	12345678	Staff	Active
\.


--
-- TOC entry 5040 (class 0 OID 16509)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260904202353_InitialPostgres	10.0.11
20260905141422_AddResolutionColumnToTicket	10.0.11
\.


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 220
-- Name: ActivityLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ActivityLogs_Id_seq"', 85, true);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 224
-- Name: Assets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Assets_Id_seq"', 8, true);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 226
-- Name: Tickets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tickets_Id_seq"', 9, true);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 222
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 6, true);


--
-- TOC entry 4878 (class 2606 OID 16527)
-- Name: ActivityLogs PK_ActivityLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ActivityLogs"
    ADD CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id");


--
-- TOC entry 4883 (class 2606 OID 16554)
-- Name: Assets PK_Assets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Assets"
    ADD CONSTRAINT "PK_Assets" PRIMARY KEY ("Id");


--
-- TOC entry 4888 (class 2606 OID 16573)
-- Name: Tickets PK_Tickets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");


--
-- TOC entry 4880 (class 2606 OID 16541)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4876 (class 2606 OID 16515)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4881 (class 1259 OID 16589)
-- Name: IX_Assets_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Assets_UserId" ON public."Assets" USING btree ("UserId");


--
-- TOC entry 4884 (class 1259 OID 16590)
-- Name: IX_Tickets_AssetId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tickets_AssetId" ON public."Tickets" USING btree ("AssetId");


--
-- TOC entry 4885 (class 1259 OID 16591)
-- Name: IX_Tickets_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tickets_CreatedById" ON public."Tickets" USING btree ("CreatedById");


--
-- TOC entry 4886 (class 1259 OID 16592)
-- Name: IX_Tickets_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tickets_UserId" ON public."Tickets" USING btree ("UserId");


--
-- TOC entry 4889 (class 2606 OID 16555)
-- Name: Assets FK_Assets_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Assets"
    ADD CONSTRAINT "FK_Assets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


--
-- TOC entry 4890 (class 2606 OID 16574)
-- Name: Tickets FK_Tickets_Assets_AssetId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Assets_AssetId" FOREIGN KEY ("AssetId") REFERENCES public."Assets"("Id");


--
-- TOC entry 4891 (class 2606 OID 16579)
-- Name: Tickets FK_Tickets_Users_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."Users"("Id");


--
-- TOC entry 4892 (class 2606 OID 16584)
-- Name: Tickets FK_Tickets_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


-- Completed on 2026-09-06 02:08:25

--
-- PostgreSQL database dump complete
--

\unrestrict TYyDwbouFhGmbIwUnRb4etM6IiYWgNocppu7STdcaOAB9nk8QUfxvWIvD3hjlC4

